services:
  meuprojetinho:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    depends_on:
      - meubanquinho 
    command: python manage.py runserver 0.0.0.0:8000
  meubanquinho:
    image: postgres:latest
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: