# Generated by Django 5.1.6 on 2025-03-23 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0003_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da cesta', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da cesta', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço da cesta', max_digits=10, verbose_name='Preço')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('M', 'Médio'), ('P', 'Premium')], default='B', help_text='Nível da cesta', max_length=1, verbose_name='Nível')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da cesta', null=True, upload_to='cestas', verbose_name='Imagem')),
                ('produtos', models.ManyToManyField(help_text='Produtos da cesta', related_name='cestas', to='padarias.produto', verbose_name='Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Padaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da padaria', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da padaria', null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da padaria', null=True, upload_to='padarias', verbose_name='Imagem')),
                ('telefone', models.CharField(blank=True, help_text='Telefone da padaria', max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='E-mail da padaria', max_length=254, null=True, verbose_name='E-mail')),
                ('cestas', models.ManyToManyField(help_text='Cestas da padaria', related_name='padarias', to='padarias.cesta', verbose_name='Cestas')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(help_text='Rua do endereço', max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, help_text='Bairro do endereço', max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade do endereço', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Estado do endereço', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(help_text='CEP do endereço', max_length=8, verbose_name='CEP')),
                ('padaria', models.OneToOneField(help_text='Padaria do endereço', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='padarias.padaria', verbose_name='Padaria')),
            ],
        ),
    ]
