services:
    rabbit:
        image: rabbitmq:3-management-alpine
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
        logging:
            driver: none 
        ports: 
            - 5672:5672
            - 8080:15672
    cafepao:
        build: ./cafepao
        volumes:
            - "./cafepao/:/code"
        depends_on:
            rabbit:
                condition: service_healthy
        command: sh -c 'python -u main.py'
        environment:
            AMQP_URL: amqp://guest:guest@rabbit:5672
    whatsapp:
        build: ./whatsapp
        volumes:
            - "./whatsapp/:/code"
        depends_on:
            rabbit:
                condition: service_healthy
        command: sh -c 'python -u main.py'
        environment:
            AMQP_URL: amqp://guest:guest@rabbit:5672
    mailing:
        build: ./mailing
        volumes:
            - "./mailing/:/code"
        depends_on:
            rabbit:
                condition: service_healthy
        command: sh -c 'python -u main.py'
        environment:
            AMQP_URL: amqp://guest:guest@rabbit:5672
    entregas:
        build: ./entregas
        volumes:
            - "./entregas/:/code"
        depends_on:
            rabbit:
                condition: service_healthy
        command: sh -c 'python -u main.py'
        deploy:
            mode: replicated
            replicas: 3
        environment:
            AMQP_URL: amqp://guest:guest@rabbit:5672
    
   
