# Generated by Django 5.1.6 on 2025-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('avaliacao', models.PositiveSmallIntegerField(default=1, verbose_name='Avaliação')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
    ]
