# Generated by Django 4.2 on 2023-08-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_matricula', models.DateField()),
                ('registro_academico', models.CharField(max_length=100)),
            ],
        ),
    ]
